apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: dev
      label:
        name: dev
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: itg
      label:
        name: itg
